// <auto-generated />
using System;
using AICourseTester.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260616115533_NormalizeAnalysisSchema")]
    partial class NormalizeAnalysisSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AICourseTester.Models.AlphaBeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("Problem")
                        .HasColumnType("text");

                    b.Property<string>("Solution")
                        .HasColumnType("text");

                    b.Property<int?>("Template")
                        .HasColumnType("integer");

                    b.Property<int>("TreeHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPath")
                        .HasColumnType("text");

                    b.Property<string>("UserPrunedNodeIds")
                        .HasColumnType("text");

                    b.Property<string>("UserSolution")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AlphaBeta");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.AnalysisRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlphaBetaId")
                        .HasColumnType("integer");

                    b.Property<string>("AnalyzerVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("FifteenPuzzleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaskTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("AnalysisRuns");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.AnalysisStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AnalysisStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Started",
                            Name = "Started"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Completed",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Failed",
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.CausalErrorLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceErrorId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetErrorId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RelationTypeId");

                    b.HasIndex("SourceErrorId");

                    b.HasIndex("TargetErrorId");

                    b.ToTable("CausalErrorLinks");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.CausalErrorRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("SameNodeRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("SameRootBranchRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("SourceErrorTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetErrorTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RelationTypeId");

                    b.HasIndex("SourceErrorTypeId");

                    b.HasIndex("TargetErrorTypeId");

                    b.HasIndex("TaskTypeId", "SourceErrorTypeId", "TargetErrorTypeId", "RelationTypeId", "SameNodeRequired", "SameRootBranchRequired")
                        .IsUnique();

                    b.ToTable("CausalErrorRules");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.CausalRelationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CausalRelationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CAUSES",
                            Name = "Causes"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EXPLAINS",
                            Name = "Explains"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MAY_CAUSE",
                            Name = "May cause"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CONTEXT_FOR",
                            Name = "Context for"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SUMMARIZES",
                            Name = "Summarizes"
                        });
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.GapLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GapLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Low",
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Medium",
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Code = "High",
                            Name = "High"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Critical",
                            Name = "Critical"
                        });
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.GapTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GapTrends");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Stable",
                            Name = "Stable"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Improved",
                            Name = "Improved"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Worsened",
                            Name = "Worsened"
                        },
                        new
                        {
                            Id = 4,
                            Code = "New",
                            Name = "New"
                        });
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.TaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TaskTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AlphaBeta",
                            Name = "Alpha-Beta pruning"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FifteenPuzzle",
                            Name = "Fifteen puzzle A*"
                        });
                });

            modelBuilder.Entity("AICourseTester.Models.AnalyticsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageGapScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("HighSeverityErrorsCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TopErrorTypesJson")
                        .HasColumnType("text");

                    b.Property<string>("TopKnowledgeGapsJson")
                        .HasColumnType("text");

                    b.Property<int>("TotalErrors")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGroups")
                        .HasColumnType("integer");

                    b.Property<int>("TotalKnowledgeGaps")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("AnalyticsSnapshots");
                });

            modelBuilder.Entity("AICourseTester.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PfpPath")
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AICourseTester.Models.ErrorRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualA")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualB")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualPathNodeId")
                        .HasColumnType("integer");

                    b.Property<int?>("AlphaBetaId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnalysisRunId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ErrorTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedA")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedB")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedPathNodeId")
                        .HasColumnType("integer");

                    b.Property<int?>("FifteenPuzzleId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsExpectedPruned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnCorrectPath")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSummary")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserPruned")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("NodeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PathStepIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PatternType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("RootBranchId")
                        .HasColumnType("integer");

                    b.Property<double>("SeverityScore")
                        .HasColumnType("double precision");

                    b.Property<int>("SimilarErrorCount")
                        .HasColumnType("integer");

                    b.Property<double>("SimilarErrorRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("SimilarOpportunityCount")
                        .HasColumnType("integer");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("TreeLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlphaBetaId");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("ErrorTypeId");

                    b.HasIndex("FifteenPuzzleId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("ErrorRecords");
                });

            modelBuilder.Entity("AICourseTester.Models.ErrorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DefaultSeverity")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ErrorTypes");
                });

            modelBuilder.Entity("AICourseTester.Models.ErrorTypeAspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrorTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("KnowledgeAspectId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeAspectId");

                    b.HasIndex("ErrorTypeId", "KnowledgeAspectId")
                        .IsUnique();

                    b.ToTable("ErrorTypeAspects");
                });

            modelBuilder.Entity("AICourseTester.Models.FifteenPuzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Dimensions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<int?>("Heuristic")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Problem")
                        .HasColumnType("text");

                    b.Property<string>("Solution")
                        .HasColumnType("text");

                    b.Property<int>("TreeHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserSolution")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fifteens");
                });

            modelBuilder.Entity("AICourseTester.Models.GeneratedRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AffectedStudentsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GapScore")
                        .HasColumnType("double precision");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("KnowledgeAspectId")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RelatedErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TopicName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("KnowledgeAspectId");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedRecommendations");
                });

            modelBuilder.Entity("AICourseTester.Models.GeneratedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalyticsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedReports");
                });

            modelBuilder.Entity("AICourseTester.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AICourseTester.Models.KnowledgeAspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("KnowledgeAspects");
                });

            modelBuilder.Entity("AICourseTester.Models.KnowledgeGap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlphaBetaId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnalysisRunId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageSeverity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<int?>("FifteenPuzzleId")
                        .HasColumnType("integer");

                    b.Property<double>("GapScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("GapScoreDelta")
                        .HasColumnType("double precision");

                    b.Property<int>("KnowledgeAspectId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<double?>("PreviousGapScore")
                        .HasColumnType("double precision");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("TotalWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("TrendId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlphaBetaId");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("FifteenPuzzleId");

                    b.HasIndex("KnowledgeAspectId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TaskTypeId");

                    b.HasIndex("TrendId");

                    b.HasIndex("UserId");

                    b.ToTable("KnowledgeGaps");
                });

            modelBuilder.Entity("AICourseTester.Models.KnowledgeTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("KnowledgeTopics");
                });

            modelBuilder.Entity("AICourseTester.Models.UserGroups", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AICourseTester.Models.AlphaBeta", b =>
                {
                    b.HasOne("AICourseTester.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.AnalysisRun", b =>
                {
                    b.HasOne("AICourseTester.Models.Analysis.AnalysisStatus", "StatusRef")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.Analysis.TaskType", "TaskTypeRef")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusRef");

                    b.Navigation("TaskTypeRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.CausalErrorLink", b =>
                {
                    b.HasOne("AICourseTester.Models.Analysis.CausalRelationType", "RelationTypeRef")
                        .WithMany("CausalErrorLinks")
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.ErrorRecord", "SourceError")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceErrorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.ErrorRecord", "TargetError")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetErrorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelationTypeRef");

                    b.Navigation("SourceError");

                    b.Navigation("TargetError");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.CausalErrorRule", b =>
                {
                    b.HasOne("AICourseTester.Models.Analysis.CausalRelationType", "RelationTypeRef")
                        .WithMany("CausalErrorRules")
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.ErrorType", "SourceErrorType")
                        .WithMany()
                        .HasForeignKey("SourceErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.ErrorType", "TargetErrorType")
                        .WithMany()
                        .HasForeignKey("TargetErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.Analysis.TaskType", "TaskTypeRef")
                        .WithMany("CausalErrorRules")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelationTypeRef");

                    b.Navigation("SourceErrorType");

                    b.Navigation("TargetErrorType");

                    b.Navigation("TaskTypeRef");
                });

            modelBuilder.Entity("AICourseTester.Models.AnalyticsSnapshot", b =>
                {
                    b.HasOne("AICourseTester.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AICourseTester.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AICourseTester.Models.ErrorRecord", b =>
                {
                    b.HasOne("AICourseTester.Models.AlphaBeta", "AlphaBeta")
                        .WithMany("Errors")
                        .HasForeignKey("AlphaBetaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AICourseTester.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany("ErrorRecords")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AICourseTester.Models.ErrorType", "ErrorType")
                        .WithMany("Errors")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AICourseTester.Models.FifteenPuzzle", "FifteenPuzzle")
                        .WithMany()
                        .HasForeignKey("FifteenPuzzleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AICourseTester.Models.Analysis.TaskType", "TaskTypeRef")
                        .WithMany("ErrorRecords")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlphaBeta");

                    b.Navigation("AnalysisRun");

                    b.Navigation("ErrorType");

                    b.Navigation("FifteenPuzzle");

                    b.Navigation("TaskTypeRef");
                });

            modelBuilder.Entity("AICourseTester.Models.ErrorTypeAspect", b =>
                {
                    b.HasOne("AICourseTester.Models.ErrorType", "ErrorType")
                        .WithMany("ErrorTypeAspects")
                        .HasForeignKey("ErrorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.KnowledgeAspect", "KnowledgeAspect")
                        .WithMany("ErrorTypeAspects")
                        .HasForeignKey("KnowledgeAspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErrorType");

                    b.Navigation("KnowledgeAspect");
                });

            modelBuilder.Entity("AICourseTester.Models.FifteenPuzzle", b =>
                {
                    b.HasOne("AICourseTester.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AICourseTester.Models.GeneratedRecommendation", b =>
                {
                    b.HasOne("AICourseTester.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AICourseTester.Models.KnowledgeAspect", "KnowledgeAspect")
                        .WithMany()
                        .HasForeignKey("KnowledgeAspectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AICourseTester.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("KnowledgeAspect");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AICourseTester.Models.GeneratedReport", b =>
                {
                    b.HasOne("AICourseTester.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AICourseTester.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AICourseTester.Models.KnowledgeAspect", b =>
                {
                    b.HasOne("AICourseTester.Models.KnowledgeTopic", "Topic")
                        .WithMany("KnowledgeAspects")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AICourseTester.Models.KnowledgeGap", b =>
                {
                    b.HasOne("AICourseTester.Models.AlphaBeta", "AlphaBeta")
                        .WithMany()
                        .HasForeignKey("AlphaBetaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AICourseTester.Models.Analysis.AnalysisRun", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AICourseTester.Models.FifteenPuzzle", "FifteenPuzzle")
                        .WithMany()
                        .HasForeignKey("FifteenPuzzleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AICourseTester.Models.KnowledgeAspect", "KnowledgeAspect")
                        .WithMany()
                        .HasForeignKey("KnowledgeAspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.Analysis.GapLevel", "LevelRef")
                        .WithMany("KnowledgeGaps")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.Analysis.TaskType", "TaskTypeRef")
                        .WithMany("KnowledgeGaps")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.Analysis.GapTrend", "TrendRef")
                        .WithMany("KnowledgeGaps")
                        .HasForeignKey("TrendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlphaBeta");

                    b.Navigation("AnalysisRun");

                    b.Navigation("FifteenPuzzle");

                    b.Navigation("KnowledgeAspect");

                    b.Navigation("LevelRef");

                    b.Navigation("TaskTypeRef");

                    b.Navigation("TrendRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AICourseTester.Models.UserGroups", b =>
                {
                    b.HasOne("AICourseTester.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AICourseTester.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AICourseTester.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AICourseTester.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AICourseTester.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AICourseTester.Models.AlphaBeta", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.AnalysisRun", b =>
                {
                    b.Navigation("ErrorRecords");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.AnalysisStatus", b =>
                {
                    b.Navigation("AnalysisRuns");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.CausalRelationType", b =>
                {
                    b.Navigation("CausalErrorLinks");

                    b.Navigation("CausalErrorRules");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.GapLevel", b =>
                {
                    b.Navigation("KnowledgeGaps");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.GapTrend", b =>
                {
                    b.Navigation("KnowledgeGaps");
                });

            modelBuilder.Entity("AICourseTester.Models.Analysis.TaskType", b =>
                {
                    b.Navigation("AnalysisRuns");

                    b.Navigation("CausalErrorRules");

                    b.Navigation("ErrorRecords");

                    b.Navigation("KnowledgeGaps");
                });

            modelBuilder.Entity("AICourseTester.Models.ErrorRecord", b =>
                {
                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");
                });

            modelBuilder.Entity("AICourseTester.Models.ErrorType", b =>
                {
                    b.Navigation("ErrorTypeAspects");

                    b.Navigation("Errors");
                });

            modelBuilder.Entity("AICourseTester.Models.KnowledgeAspect", b =>
                {
                    b.Navigation("ErrorTypeAspects");
                });

            modelBuilder.Entity("AICourseTester.Models.KnowledgeTopic", b =>
                {
                    b.Navigation("KnowledgeAspects");
                });
#pragma warning restore 612, 618
        }
    }
}
